# Generated by Django 5.0.6 on 2024-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=32)),
            ],
        ),
    ]
